name: CI
on: [push, pull_request]
jobs:
  build:
    uses: open-contracting/.github/.github/workflows/ci-profile.yml@main
    secrets:
      private-key: ${{ secrets.PRIVATE_KEY }}
      elasticsearch-password: ${{ secrets.ELASTICSEARCH_PASSWORD }}
    with:
      path-prefix: profiles/eforms/
