name: Spell-check
on: [push, pull_request]
jobs:
  lint:
    uses: open-contracting/.github/.github/workflows/spellcheck.yml@main
    with:
      ignore: abd,fo,sme,tne,zar
      skip: docson,locale,country.csv,currency.csv,language.csv
